# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96eed5b8d3a3ca070c73d074ce20a255272bd4d76abec6aa42ead7d4d3ef56c23db501d87d3be7a42cd2fd0b28fd93154620ed898498dfa57afc883a717cebf0

test:
  secret_key_base: cc346df228acb6239bce89a9d97f82e37c7a4200e158a24b8dc5bb58625059c0cfe731bdcc9ef6dca1b24bad78a7b4162dab4d78cebcfb511e367b40796be9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
